#!/bin/bash

source "$CONFIG_DIR/colors.sh" # Load all defined colors

# This is a demo config to showcase some of the most important commands.
# It is meant to be changed and configured, as it is intentionally kept sparse.
# For a (much) more advanced configuration example see my dotfiles:
# https://github.com/FelixKratz/dotfiles

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"

##### Bar Appearance #####

sketchybar --bar position=top \
                 border_color=$GHOST_WHITE \
                 border_width=1 \
                 height=32 \
                 blur_radius=30 \
                 color=0x40000000 \
                 corner_radius=9 \
                 margin=30 \
                 y_offset=10 \
                 color=$BAR_COLOR \
                 padding_left=9 \
                 padding_right=9

##### Changing Defaults #####

default=(
  icon.font="SF Pro:Semibold:15.0"
  label.font="SF Pro:Semibold:15.0"
  icon.color=$WHITE
  label.color=$WHITE
  icon.padding_left=6
  icon.padding_right=4
  label.padding_left=4
  label.padding_right=7
)
sketchybar --default "${default[@]}"

# -- Left Side Items --
source $ITEM_DIR/front_app.sh

# -- Center Items
source $ITEM_DIR/calendar.sh
source $ITEM_DIR/time.sh

# -- Right Side Items --
source $ITEM_DIR/battery.sh
source $ITEM_DIR/volume.sh

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
